name: FortiDevSec Scanner CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  fortidevsec-sast-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run FortiDevSec SAST Scan
        run: |
          echo "Pulling FortiDevSec SAST Docker image..."
          docker pull registry.fortidevsec.forticloud.com/fdevsec_sast:latest
          
          echo "Running SAST scan..."
          docker run --rm \
            --mount type=bind,source=$PWD,target=/scan \
            registry.fortidevsec.forticloud.com/fdevsec_sast:latest

